name: Check code style
on:
    push:
        branches:
            - main
            - master
    pull_request:
        branches:
            - main
            - master
jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - name: install dependencies
              run: npm install
            - name: stylelint
              run: npm run lint-stylelint
            - name: eslint
              run: npm run lint-eslint
            - name: tsc
              run: npm run lint-tsc
